from setuptools import setup, find_packages

setup(
    name="bit_image_captioning",
    version="0.1.0",
    description="Arabic Image Captioning using Pre-training of Deep Bidirectional Transformers",
    author="Mahmood Anaam",
    author_email="eng.mahmood.anaam@gmail.com",
    url="https://github.com/Mahmood-Anaam/BiT-ImageCaptioning",
    license="MIT",
    packages=find_packages(where="src",exclude="scene_graph_benchmark"),
    package_dir={"": "src"},
    install_requires=[
            "torch>=2.5.0",
            "torchvision>=0.20.0",
            "yacs",
            "cityscapesScripts",
            "clint",
            "transformers",
            "numpy",
            "opencv-python",
            "Pillow",
            "tqdm",
            "anytree",
            "pycocotools",
            "timm",
            "einops",
            "PyYAML",
            "cython>=0.29",
            "ninja>=1.10.0",
            "pytorch_transformers",
            "datasets",
        ],
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.7",
)

